final Map<String, dynamic> recipes = {
  "recipes": [
    {
      "id": 1,
      "name": "Classic Margherita Pizza",
      "ingredients": [
        "Pizza dough",
        "Tomato sauce",
        "Fresh mozzarella cheese",
        "Fresh basil leaves",
        "Olive oil",
        "Salt and pepper to taste"
      ],
      "instructions": [
        "Preheat the oven to 475°F (245°C).",
        "Roll out the pizza dough and spread tomato sauce evenly.",
        "Top with slices of fresh mozzarella and fresh basil leaves.",
        "Drizzle with olive oil and season with salt and pepper.",
        "Bake in the preheated oven for 12-15 minutes or until the crust is golden brown.",
        "Slice and serve hot."
      ],
      "prepTimeMinutes": 20,
      "cookTimeMinutes": 15,
      "servings": 4,
      "difficulty": "Easy",
      "cuisine": "Italian",
      "caloriesPerServing": 300,
      "tags": ["Pizza", "Italian"],
      "userId": 166,
      "image": "https://cdn.dummyjson.com/recipe-images/1.webp",
      "rating": 4.6,
      "reviewCount": 98,
      "mealType": ["Dinner"]
    }
  ]
};

final List<dynamic> recipesTags = [
  "Pizza",
  "Italian",
  "Vegetarian",
  "Stir-fry",
  "Asian",
  "Cookies",
  "Dessert",
  "Baking",
  "Pasta",
  "Chicken",
  "Salsa",
  "Salad",
  "Quinoa",
  "Bruschetta",
  "Beef",
  "Caprese",
  "Shrimp",
  "Biryani",
  "Main course",
  "Indian",
  "Pakistani",
  "Karahi",
  "Keema",
  "Potatoes",
  "Kebabs",
  "Saag",
  "Roti",
  "Ramen",
  "Japanese",
  "Soup",
  "Tagine",
  "Chickpea",
  "Moroccan",
  "Bibimbap",
  "Korean",
  "Rice",
  "Moussaka",
  "Greek",
  "Butter chicken",
  "Curry",
  "Thai",
  "Lassi",
  "Mango",
  "Tiramisu",
  "Turkish",
  "Grilling",
  "Smoothie",
  "Blueberry",
  "Banana",
  "Elote",
  "Mexican",
  "Street food",
  "Borscht",
  "Russian",
  "Dosa",
  "Falafel",
  "Lebanese",
  "Wrap",
  "Caipirinha",
  "Brazilian",
  "Cocktail",
  "Patatas bravas",
  "Spanish",
  "Spring rolls",
  "Vietnamese",
  "Quinoa salad",
  "Mediterranean",
  "Matcha ice cream",
  "Brigadeiros",
  "Enchiladas",
  "Shrimp curry",
  "Spanakopita",
  "Couscous salad",
  "Mojito",
  "Cuban",
  "Teriyaki chicken",
  "Mango salsa",
  "Shrimp stir-fry",
  "Quick",
  "Margherita pizza",
  "Pesto pasta",
  "Chicken skewers",
  "Hawaiian",
  "Sushi rolls",
  "Chickpea salad",
  "Pineapple",
  "Coconut"
];

final Map<String, dynamic> recipesByTag = {
  "recipes": [
    {
      "id": 1,
      "name": "Classic Margherita Pizza",
      "ingredients": [
        "Pizza dough",
        "Tomato sauce",
        "Fresh mozzarella cheese",
        "Fresh basil leaves",
        "Olive oil",
        "Salt and pepper to taste"
      ],
      "instructions": [
        "Preheat the oven to 475°F (245°C).",
        "Roll out the pizza dough and spread tomato sauce evenly.",
        "Top with slices of fresh mozzarella and fresh basil leaves.",
        "Drizzle with olive oil and season with salt and pepper.",
        "Bake in the preheated oven for 12-15 minutes or until the crust is golden brown.",
        "Slice and serve hot."
      ],
      "prepTimeMinutes": 20,
      "cookTimeMinutes": 15,
      "servings": 4,
      "difficulty": "Easy",
      "cuisine": "Italian",
      "caloriesPerServing": 300,
      "tags": ["Pizza", "Italian"],
      "userId": 166,
      "image": "https://cdn.dummyjson.com/recipe-images/1.webp",
      "rating": 4.6,
      "reviewCount": 98,
      "mealType": ["Dinner"]
    }
  ],
  "total": 1,
  "skip": 0,
  "limit": 1
};
